apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gophprofile.configMapName" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
data:
  HTTP_ADDR: {{ .Values.config.httpAddr | quote }}
  METRICS_ADDR: {{ .Values.config.metricsAddr | quote }}
  S3_ENDPOINT: {{ include "gophprofile.s3Endpoint" . | quote }}
  S3_BUCKET: {{ .Values.config.s3Bucket | quote }}
  S3_USE_SSL: {{ .Values.config.s3UseSSL | quote }}
  S3_PUBLIC_ENDPOINT: {{ .Values.config.s3PublicEndpoint | quote }}
  RABBITMQ_EXCHANGE: {{ .Values.config.rabbitmqExchange | quote }}
  PUBLIC_URL: {{ .Values.config.publicURL | quote }}
  WEB_DIR: {{ .Values.config.webDir | quote }}
  MAX_FILE_SIZE: {{ .Values.config.maxFileSize | quote }}
  RATE_LIMIT: {{ .Values.config.rateLimit | quote }}
  OTEL_SERVICE_NAME: {{ .Values.config.otelServiceName | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelEndpoint | quote }}
