{{- if .Values.infra.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gophprofile.rabbitmq.fullname" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    app: gophprofile-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gophprofile.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "gophprofile.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
        app: gophprofile-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.infra.rabbitmq.image }}
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.infra.rabbitmq.resources | nindent 12 }}
          {{- if .Values.infra.rabbitmq.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
          {{- end }}
      {{- if .Values.infra.rabbitmq.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "gophprofile.rabbitmq.fullname" . }}
      {{- end }}
{{- if .Values.infra.rabbitmq.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gophprofile.rabbitmq.fullname" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.infra.rabbitmq.persistence.storageClass }}
  storageClassName: {{ .Values.infra.rabbitmq.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.infra.rabbitmq.persistence.size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.rabbitmq.fullname" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    app: gophprofile-rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
  selector:
    {{- include "gophprofile.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
{{- end }}
