{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.secretName" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "gophprofile.databaseURL" . | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | quote }}
  BROKER_URL: {{ include "gophprofile.brokerURL" . | quote }}
  {{- if .Values.infra.enabled }}
  POSTGRES_USER: {{ .Values.infra.postgres.auth.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.infra.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.infra.postgres.auth.database | quote }}
  MINIO_ROOT_USER: {{ .Values.secrets.s3AccessKey | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.s3SecretKey | quote }}
  {{- end }}
{{- end }}
