apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.fullname" . }}-server
  labels:
    {{- include "gophprofile.server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "gophprofile.server.selectorLabels" . | nindent 4 }}
