apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.fullname" . }}-worker
  labels:
    {{- include "gophprofile.worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.worker.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "gophprofile.worker.selectorLabels" . | nindent 4 }}
