[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

[INPUT]
    Name                forward
    Listen              0.0.0.0
    Port                24224

[FILTER]
    Name                parser
    Match               gophprofile.*
    Key_Name            log
    Parser              json
    Reserve_Data        On

[FILTER]
    Name                modify
    Match               gophprofile.server
    Add                 service server
    Add                 job gophprofile

[FILTER]
    Name                modify
    Match               gophprofile.worker
    Add                 service worker
    Add                 job gophprofile

[OUTPUT]
    Name                opensearch
    Match               gophprofile.*
    Host                opensearch
    Port                9200
    Index               gophprofile-logs
    Suppress_Type_Name  On
    Logstash_Format     On
    Logstash_Prefix     gophprofile-logs
    Logstash_DateFormat %Y.%m.%d
    Replace_Dots        On
    Retry_Limit         False
    Trace_Error         On
    TLS                 Off
    HTTP_Compress       False
